"""
You are given a string s consisting only of letters 'a' and 'b'. In a single step you can remove one palindromic subsequence from s.

Return the minimum number of steps to make the given string empty.

A string is a subsequence of a given string if it is generated by deleting some characters of a given string without changing its order. Note that a subsequence does not necessarily need to be contiguous.

A string is called palindrome if is one that reads the same backward as well as forward.

Examples:
Input: s = "ababa"
Output: 1

Input: s = "abb"
Output: 2

Input: s = "baabb"
Output: 2

Problem source: LeetCode

Usage: remove_palindromic_subsequence.py <s>
"""

def remove_palindrome_sub(s: str) -> int:
  return int(s == s[::-1]) or 2